services:

  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: structured-logs-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - net

  app:
    build: .
    container_name: structured-logs
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - net
    environment:
        - RABBITMQ_HOST=rabbitmq
        - RABBITMQ_PORT=5672
        - RABBITMQ_USER=guest
        - RABBITMQ_PASS=guest
        - SPRING_PROFILES_ACTIVE=logstash-amqp

networks:
  net:
    driver: bridge
